FROM node:16 AS builder

WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install --legacy-peer-deps

COPY . .

ARG BASE_URL
ENV REACT_APP_API=${BASE_URL}

RUN npm run build

## Copy into secondary caddy server

FROM caddy:2.1.1

ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile

COPY --from=builder /usr/src/app/build/ /srv

EXPOSE 80

EXPOSE 443